Make bot send error message of module doesn't have a manifest file
ThatOtherAndrew/ThatOtherBot pull request #57
Opened 2023-04-22 16:07 UTC by Fripe070

Running `/module install` with an existing, but non-module, GitHub repo as the argument would throw a `KeyError`.
This PR posts an error message embed in chat rather than throwing an exception.

2023-04-22 16:09 UTC, Fripe070 commented
You can try this by running for example: `/module install module: torvalds/linux`

2023-04-24 15:58 UTC, ThatOtherAndrew requested changes

2023-04-24 15:58 UTC, ThatOtherAndrew commented on breadcord/core_modules/modulemanager/__init__.py
> +                    description='The repository specified does not contain a `manifest.toml` file.'
While this is certainly an improvement over what we've got before, it doesn't cover cases such as e.g. the GitHub repository not existing or GitHub being down. It'd probably be more helpful to change the error message to something like:
```
Module not found!

The repository specified does not exist, or isn't a Breadcord module.
```

In a future commit I could then improve upon that by making additional checks be performed if the `manifest.toml` file fails to be read.

2023-04-26 15:44 UTC, ThatOtherAndrew approved these changes

2023-04-26 15:44 UTC, merged